// <auto-generated />
namespace Ewidencja.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UsersTest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UsersTest));
        
        string IMigrationMetadata.Id
        {
            get { return "201307301408434_Users Test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
